AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Compliment Bot Serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 256

Resources:
  BotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          OPENAI_API_KEY: "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"
      CodeUri: bot/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.9
      Layers:
        - arn:aws:lambda:eu-west-2:120718319034:layer:openai:2
      Architectures:
        - x86_64
      Events:
        Bot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: bot/
            Method: get
